spring.application.name=spring-security-app
spring.security.user.name=user
spring.security.user.password=password

spring.devtools.restart.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/privy_notes_DB
spring.datasource.username=postgres
spring.datasource.password=sahil@postgresql

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
