spring.application.name=spring-security-app

# --- SERVER CONFIGURATION ---
# Listen on all network interfaces (Required for Render/Docker)
server.address=0.0.0.0

# Listen on Render's assigned port, but default to 8080 when running locally
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.devtools.restart.enabled=true

springdoc.api-docs.path=/api-docs

