spring.application.name=spring-security-app

# ---------------- SERVER CONFIG ----------------
# Required for Render
server.address=0.0.0.0

# Render provides PORT automatically
server.port=${PORT:8080}

# ---------------- DATABASE ----------------
spring.datasource.url=${DB_URL}

spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------- JPA / HIBERNATE ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---------------- DEVTOOLS ----------------
spring.devtools.restart.enabled=true

# ---------------- SWAGGER / OPENAPI ----------------
# Public API docs endpoint
springdoc.api-docs.path=/api-docs

# Enable Swagger UI publicly
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true